### ISSUE TITLE
In AWS::B2BI::Transformer, the status is created as 'inactive' even though the status is created as 'active'. 

### ISSUE THREAD

**Issue by yushikato0131** [aws-cloudformation/aws-cloudformation-resource-providers-b2bi#21]
Name of the resource
AWS::B2BI::Transformer

Resource Name
AWS::B2BI::Transformer

Issue Description
In AWS::B2BI::Transformer, the status is created as 'inactive' even though the status is created as 'active'.

This causes the error "Transformer status must be 'active'" in AWS::B2BI::Capability.

The resource is not added in the list of Name of the resource.

Expected Behavior
As stated in the Issue Description

Observed Behavior
As stated in the Issue Description

Test Cases
As stated in the Issue Description

Other Details
https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1878

**Comment by dmoini** [comment]
At this moment, this is currently by design. An `AWS::B2BI::Transformer` is created in an inactive state by default and must be updated to an active state in a separate action. However, we realize that this is not a good customer experience for customers trying to create B2BI CloudFormation resources. We are discussing this concern internally.

**Comment by dmoini** [comment]
We have now added support for customers to create active B2BI transformers in CloudFormation. When creating a transformer, please specify the `status` field with the value `active` to create an active transformer. Feel free to reopen this issue if there are any issues or concerns.
